eMovieTickets/Models/Actor.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace eMovieTickets.Models
{
    public class Actor
    {
        [Key]
        public int Id { get; set; }
        [Display(Name ="Profile Picture")]
        [Required(ErrorMessage ="Profile picture is required")]
        public string ProfilePictureURL { get; set; }
		[Display(Name = "Full Name")]
		[Required(ErrorMessage = "Full name is required")]
        [StringLength(50,MinimumLength =3,ErrorMessage ="Full name must be between 3 and 50 chars")]
		public string FullName { get; set; }
		[Display(Name = "Biography")]
		[Required(ErrorMessage = "Biography is required")]
		public string Bio { get; set; }

        //Relationships
        public List<Actor_Movie> Actors_Movies { get; set; }
    }
}

eMovieTickets/Models/Actor_Movie.cs
namespace eMovieTickets.Models
{
    public class Actor_Movie
    {
        public int MovieId { get; set; }
        public Movie Movie { get; set; }

        public int ActorId { get; set; }
        public Actor Actor { get; set; }
    }
}

eMovieTickets/Models/Cinema.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace eMovieTickets.Models
{
    public class Cinema
    {
        [Key]
        public int Id { get; set; }
        [Display(Name="Cinema Logo")]
        public string CinemaLogo { get; set; }
		[Display(Name ="Cinema")]
		public string Name { get; set; }
		[Display(Name ="Description")]
		public string Description { get; set; }

        //Relationships
        public List<Movie> Movies { get; set; }
    }
}

eMovieTickets/Models/ErrorViewModel.cs
using System;

namespace eMovieTickets.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

eMovieTickets/Models/Movie.cs
using eMovieTickets.Data.Enums;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace eMovieTickets.Models
{
    public class Movie
    {
        [Key]
        public int Id { get; set; }

        public string Name { get; set; }
        public string Description { get; set; }
        public double Price { get; set; }
        public string ImageURL { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public MovieCategory MovieCategory { get; set; }

        //Relationships
        public List<Actor_Movie> Actors_Movies { get; set; }

        //Cinema
        public int CinemaId { get; set; }
        [ForeignKey("CinemaId")]
        public Cinema Cinema { get; set; }

        //Producer
        public int ProducerId { get; set; }
        [ForeignKey("ProducerId")]
        public Producer Producer { get; set; }

    }
}

eMovieTickets/Models/Producer.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace eMovieTickets.Models
{
    public class Producer
    {
        [Key]
        public int Id { get; set; }
		[Display(Name ="Profile Picture")]
		public string ProfilePictureURL { get; set; }
		[Display(Name = "Full Name")]
		public string FullName { get; set; }
		[Display(Name = "Biography")]
		public string Bio { get; set; }

        //Relationships
        public List<Movie> Movies { get; set; }
    }
}

eMovieTickets/Controllers/ActorsController.cs
using eMovieTickets.Data;
using eMovieTickets.Data.Services;
using eMovieTickets.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace eMovieTickets.Controllers
{
	public class ActorsController : Controller
	{
		private readonly IActorsServices _services;

		public ActorsController(IActorsServices services)
		{
			_services = services;
		}
		public async Task<IActionResult> Index()
		{
			var allActors = await _services.GetActorsAsync();
			return View(allActors);
		}
		//Get : Actors/create
		public IActionResult Create()
		{
			return View();
		}
		[HttpPost]
		public async Task<IActionResult> Create([Bind("ProfilePictureURL,FullName,Bio")] Actor actor)
		{
			if (!ModelState.IsValid)
			{
				return View(actor);
			}
			await _services.AddActorAsync(actor);
			return RedirectToAction(nameof(Index));
			
		}
		//Get:Actors/Details/1
		public async Task<IActionResult> Details(int id)
		{
			var actorDetails =await _services.GetActorByIdAsync(id);
			if(actorDetails==null)
			{
				return View("NotFound");
			}
			return View(actorDetails);
		}
		//Get : Actors/Edit/1
		public async Task<IActionResult> Edit(int id)
		{
			var actorDetails = await _services.GetActorByIdAsync(id);
			if (actorDetails == null)
			{
				return View("NotFound");
			}
			return View(actorDetails);
		}
		[HttpPost]
		public async Task<IActionResult> Edit(int id,[Bind("Id,ProfilePictureURL,FullName,Bio")] Actor actor)
		{
			if (!ModelState.IsValid)
			{
				return View(actor);
			}
			await _services.UpdateActorAsync(id, actor);
			return RedirectToAction(nameof(Index));

		}
		//Get : Actors/Delete/1
		public async Task<IActionResult> Delete(int id)
		{
			var actorDetails = await _services.GetActorByIdAsync(id);
			if (actorDetails == null)
			{
				return View("NotFound");
			}
			return View(actorDetails);
		}
		[HttpPost,ActionName("Delete")]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			var actorDetails = await _services.GetActorByIdAsync(id);
			if (actorDetails == null)
			{
				return View("NotFound");
			}
			await _services.DeleteActorAsync(id);
			return RedirectToAction(nameof(Index));

		}

	}
}

eMovieTickets/Controllers/CinemasController.cs
using eMovieTickets.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace eMovieTickets.Controllers
{
    public class CinemasController : Controller
    {
        private readonly AppDbContext _context;

        public CinemasController(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var allCinemas = await _context.Cinemas.ToListAsync();
            return View(allCinemas);
        }
    }
}

eMovieTickets/Controllers/MoviesController.cs
using eMovieTickets.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace eMovieTickets.Controllers
{
    public class MoviesController : Controller
    {
        private readonly AppDbContext _context;

        public MoviesController(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var allMovies = await _context.Movies.Include(x => x.Cinema).OrderBy(x => x.Name).ToListAsync();
            return View(allMovies);
        }
    }
}

eMovieTickets/Controllers/ProducersController.cs
using eMovieTickets.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace eMovieTickets.Controllers
{
    public class ProducersController : Controller
    {
        private readonly AppDbContext _context;

        public ProducersController(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var allProducers =await  _context.Producers.ToListAsync();
            return View(allProducers);
        }
    }
}

eMovieTickets/Views/Actors/Create.cshtml
@model Actor
@{
	ViewData["Title"] = "Add new Actor";
}

<div class="roe-text">
	<div class="col-md-8 offset-2">
		<p>
			<h5>Add New Actor</h5>
		</p>
		<div class="row">
			<div class="col-md-8 offset-2">
				<form asp-action="Create">
					<div asp-validation-summary="ModelOnly" class="text-danger"></div>
					<div class="form-group">
						<img id="ProfilePicturePreview" />
					</div>
					<div class="form-group">
						<label asp-for="ProfilePictureURL" class="control-label"></label>
						<input asp-for="ProfilePictureURL" class="form-control" />
						<span asp-validation-for="ProfilePictureURL" class="text-danger"></span>
					</div>
					<div class="form-group">
						<label asp-for="FullName" class="control-label"></label>
						<input asp-for="FullName" class="form-control" />
						<span asp-validation-for="FullName" class="text-danger"></span>
					</div>
					<div class="form-group">
						<label asp-for="Bio" class="control-label"></label>
						<input asp-for="Bio" class="form-control" />
						<span asp-validation-for="Bio" class="text-danger"></span>
					</div>
					<div class="form-group">
						<input type="submit" class="btn btn-outline-success float-right" value="Create" />
						<a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
@section Scripts{
	<script>
		$("#ProfilePictureURL").on("change", function () {
			var output = document.getElementById('ProfilePicturePreview');
			output.src=$(this).val();
		});
	</script>
}

eMovieTickets/Views/Actors/Delete.cshtml
@model Actor
@{
	ViewData["Title"] = "Delete Actor";
}

<div class="row-text">
	<div class="col-md-8 offset-2">
		<p>
			<h5>Delete Confirmation for @Model.FullName</h5>
		</p>
		<div class="row">
			<div class="col-md-8 offset-2">
				
					<div class="form-group text-center">
					<img id="ProfilePicturePreview" alt="No Image" class="rounded-circle" style="max-width:120px;" />
					</div>
					<div class="form-group">
						<label asp-for="ProfilePictureURL" class="control-label"></label>
						<input asp-for="ProfilePictureURL" class="form-control" readonly/>
						<span asp-validation-for="ProfilePictureURL" class="text-danger"></span>
					</div>
					<div class="form-group">
						<label asp-for="FullName" class="control-label"></label>
						<input asp-for="FullName" class="form-control" readonly/>
						<span asp-validation-for="FullName" class="text-danger"></span>
					</div>
					<div class="form-group">
						<label asp-for="Bio" class="control-label"></label>
						<input asp-for="Bio" class="form-control" readonly/>
						<span asp-validation-for="Bio" class="text-danger"></span>
					</div>
					<div class="form-group">
						<form asp-action="Delete">
							<input type="hidden" asp-for="Id" />
							<input type="submit" class="btn btn-danger float-right" value="Confirm" />
						</form>
						<a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
					</div>
				
			</div>
		</div>
	</div>
</div>
@section Scripts{
	<script>
		$(document).ready(function () {
			var output = document.getElementById('ProfilePicturePreview');
			output.src = $("#ProfilePictureURL").val();
		});
		 
	</script>
}

eMovieTickets/Views/Actors/Details.cshtml
@model Actor
@{
	ViewData["Title"] = "Add new Actor";
}

<div class="row-text">
	<div class="col-md-8 offset-2">
		<p>
			<h5>Details of @Model.FullName</h5>
		</p>
		<div class="row">
			<div class="col-md-8 offset-2">
				
					<div class="form-group text-center">
					<img id="ProfilePicturePreview" alt="No Image" class="rounded-circle" style="max-width:120px;" />
					</div>
					<div class="form-group">
						<label asp-for="ProfilePictureURL" class="control-label"></label>
						<input asp-for="ProfilePictureURL" class="form-control" readonly/>
						<span asp-validation-for="ProfilePictureURL" class="text-danger"></span>
					</div>
					<div class="form-group">
						<label asp-for="FullName" class="control-label"></label>
						<input asp-for="FullName" class="form-control" readonly/>
						<span asp-validation-for="FullName" class="text-danger"></span>
					</div>
					<div class="form-group">
						<label asp-for="Bio" class="control-label"></label>
						<input asp-for="Bio" class="form-control" readonly/>
						<span asp-validation-for="Bio" class="text-danger"></span>
					</div>
					<div class="form-group">
						
					<a class="btn btn-outline-success float-right" asp-action="Edit" asp-route-id="@Model.Id">Edit</a>
						<a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
					</div>
				
			</div>
		</div>
	</div>
</div>
@section Scripts{
	<script>
		$(document).ready(function () {
			var output = document.getElementById('ProfilePicturePreview');
			output.src = $("#ProfilePictureURL").val();
		});
		 
	</script>
}

eMovieTickets/Views/Actors/Edit.cshtml
@model Actor
@{
	ViewData["Title"] = "Update Actor";
}

<div class="row-text">
	<div class="col-md-8 offset-2">
		<p>
			<h5>Update Actor</h5>
		</p>
		<div class="row">
			<div class="col-md-8 offset-2">
				<form asp-action="Edit">
					<div asp-validation-summary="ModelOnly" class="text-danger"></div>
					<div class="form-group text-center">
						<img id="ProfilePicturePreview" alt="No Image" class="rounded-circle" style="max-width:120px;max-height:120px;" />
					</div>
					<div class="form-group">
						<label asp-for="ProfilePictureURL" class="control-label"></label>
						<input asp-for="ProfilePictureURL" class="form-control" />
						<span asp-validation-for="ProfilePictureURL" class="text-danger"></span>
					</div>
					<div class="form-group">
						<label asp-for="FullName" class="control-label"></label>
						<input asp-for="FullName" class="form-control" />
						<span asp-validation-for="FullName" class="text-danger"></span>
					</div>
					<div class="form-group">
						<label asp-for="Bio" class="control-label"></label>
						<input asp-for="Bio" class="form-control" />
						<span asp-validation-for="Bio" class="text-danger"></span>
					</div>
					<div class="form-group">
						<input type="submit" class="btn btn-outline-success float-right" value="Update" />
						<a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
@section Scripts{
	<script>
		$(document).ready(function(){
			var output = document.getElementById('ProfilePicturePreview');
			output.src = $("#ProfilePictureURL").val();
		});
		$("#ProfilePictureURL").on("change", function () {
			var output = document.getElementById('ProfilePicturePreview');
			output.src=$(this).val();
		});
	</script>
}

eMovieTickets/Views/Actors/Index.cshtml
@model IEnumerable<Actor>
@{
	ViewData["Title"] = "List of Actors";
}

<div class="row">
	<div class="col-md-8 offset-md-2">
		<table class="table">
			<thead>
				<tr class="text-center">
					<th>@Html.DisplayNameFor(model=>model.ProfilePictureURL)</th>
					<th>@Html.DisplayNameFor(model=>model.FullName)</th>
					<th>@Html.DisplayNameFor(model=>model.Bio)</th>
					<th>Actions</th>
				</tr>
			</thead>
			<tbody>
				@foreach(var item in Model)
				{
					<tr>
						<td class="align-middle">
							<img class="rounded-circle" src="@item.ProfilePictureURL" alt="@item.FullName" style="max-width:120px"/>
					</td>
						<td class="align-middle">@Html.DisplayFor(model=>item.FullName)</td>
						<td class="align-middle">@Html.DisplayFor(model=>item.Bio)</td>
						<td class="align-middle">
							<a class="btn btn-outline-primary" asp-action="Edit" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i>Edit</a> |
						    <a class="btn btn-outline-info" asp-action="Details" asp-route-id="@item.Id"><i class="bi bi-eye"></i>Details</a> |
							<a class="btn btn-danger text-white" asp-action="Delete" asp-route-id="@item.Id"><i class="bi bi-trash"></i>Delete</a>
						</td>
					</tr>
				}
			</tbody>
		</table>
	</div>
</div>
<div class="text-white float-right" style="margin-right:25px;bottom:25Px;">
	<a class="btn btn-success" asp-controller="Actors" asp-action="Create"><i class="bi bi-plus-circle"></i>Add New</a>
</div>

eMovieTickets/Views/Cinemas/Index.cshtml
@model IEnumerable<Cinema>
@{
	ViewData["Title"] = "List of Cinemas";
}

<div class="row">
	<div class="col-md-8 offset-md-2">
		<table class="table">
			<thead>
				<tr class="text-center">
					<th>@Html.DisplayNameFor(model=>model.CinemaLogo)</th>
					<th>@Html.DisplayNameFor(model=>model.Name)</th>
					<th>@Html.DisplayNameFor(model=>model.Description)</th>
					<th>Actions</th>
				</tr>
			</thead>
			<tbody>
				@foreach (var item in Model)
				{
					<tr>
						<td class="align-middle">
							<img class="rounded-circle" src="@item.CinemaLogo" alt="@item.Name" style="max-width:120px" />
						</td>
						<td class="align-middle">@Html.DisplayFor(model=>item.Name)</td>
						<td class="align-middle">@Html.DisplayFor(model=>item.Description)</td>
						<td class="align-middle">
							<a class="btn btn-outline-primary"><i class="bi bi-pencil-square"></i>Edit</a> |
							<a class="btn btn-outline-info"><i class="bi bi-eye"></i>Details</a> |
							<a class="btn btn-danger text-white"><i class="bi bi-trash"></i>Delete</a>
						</td>
					</tr>
				}
			</tbody>
		</table>
	</div>
</div>

eMovieTickets/Views/Movies/Index.cshtml
@model IEnumerable<Movie>
@{
	ViewData["Title"] = "List of Movies";
}

<div class="row">
	@foreach(var item in Model)
	{
        <div class="col-md-4 col-xs-6">
        <div class="card mb-3 m-1" style="max-width: 450px;">
                <h5 class="card-header text-white bg-info">@item.Name<a class="text-white float-right"><i class="bi bi-pencil-square"></i></a></h5>
               
            <div class="row no-gutters">
                <div class="col-md-6">
                    <img src="@item.ImageURL" class="card-img" alt="@item.Name" width="100%">
                </div>
                <div class="col-md-6">
                   
                    <div class="card-body">
                         <p class="card-text"><b>Description:</b>@item.Description</p>
                            <p class="card-text"><b>Price:</b>@item.Price</p>
                            <p class="card-text"><b>Start Date:</b>@item.StartDate.ToString("dd MMM yy")</p>
                            <p class="card-text"><b>End Date:</b>@item.EndDate.ToString("dd MMM yy")</p>
                        <p class="card-text"><small class="text-muted"><b>Category:</b>@item.MovieCategory</small></p>
                            <p class="card-text"><b>Status:</b>
                                @if (DateTime.Now >= item.StartDate && DateTime.Now <= item.EndDate)
                                {
                                    <span class="badge bg-success text-white">AVAILABLE</span>
                                } else if(DateTime.Now>item.EndDate)
                                {
                                    <span class="badge bg-danger text-white">EXPIRED</span>
                                }
                                else
                                {
                                    <span class="badge bg-primary text-white">UPCOMING</span>
                                }
                            </p>
                    </div>
                </div>
            </div>
                <div class="card-footer text-muted">
                    <a class="btn btn-success text-white"><i class="bi bi-cart"></i>Add to Cart(Price:@item.Price.ToString("c"))</a>
                    <a class="btn btn-outline-primary float-right text-info"><i class="bi bi-eye"></i>View Details</a>
            </div>
        </div>
        </div>
	}
</div>

eMovieTickets/Views/Producers/Index.cshtml
@model IEnumerable<Producer>
@{
	ViewData["Title"] = "List of Producers";
}

<div class="row">
	<div class="col-md-8 offset-md-2">
		<table class="table">
			<thead>
				<tr class="text-center">
					<th>@Html.DisplayNameFor(model=>model.ProfilePictureURL)</th>
					<th>@Html.DisplayNameFor(model=>model.FullName)</th>
					<th>@Html.DisplayNameFor(model=>model.Bio)</th>
					<th>Actions</th>
				</tr>
			</thead>
			<tbody>
				@foreach (var item in Model)
				{
					<tr>
						<td class="align-middle">
							<img class="rounded-circle" src="@item.ProfilePictureURL" alt="@item.FullName" style="max-width:120px" />
						</td>
						<td class="align-middle">@Html.DisplayFor(model=>item.FullName)</td>
						<td class="align-middle">@Html.DisplayFor(model=>item.Bio)</td>
						<td class="align-middle">
							<a class="btn btn-outline-primary"><i class="bi bi-pencil-square"></i>Edit</a> |
							<a class="btn btn-outline-info"><i class="bi bi-eye"></i>Details</a> |
							<a class="btn btn-danger text-white"><i class="bi bi-trash"></i>Delete</a>
						</td>
					</tr>
				}
			</tbody>
		</table>
	</div>
</div>

eMovieTickets/Views/Shared/NotFound.cshtml
<div class="row">
    <div class="col-md-6 offset-3">
        <h2 class="text-danger">You have reached the end of the Internet..</h2>
        <hr />
        <a class="btn btn-outline-success" asp-controller="Movies" asp-action="Index">Home Page</a>
    </div>
</div>

eMovieTickets/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - eMovieTickets</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Movies" asp-action="Index">eMovieTickets</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Movies" asp-action="Index"><i class="bi bi-film"></i>Movies</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="dropdownMenuButton" data-toggle="dropdown" 
                            aria-haspopup="true" aria-expanded="false">
                                <i class="bi bi-gear"></i>Management
                           </a>
                        
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">

                                <a class="dropdown-item" asp-controller="Cinemas" asp-action="Index"><i class="bi bi-camera-reels"></i>Cinemas</a>
                                <a class="dropdown-item" asp-controller="Producers" asp-action="Index"><i class="bi bi-headset"></i>Producers</a>
                                <a class="dropdown-item" asp-controller="Actors" asp-action="Index"><i class="bi bi-person-square"></i>Actors</a>
                            </div>
                        </li>
                    </ul>
                    <form class="form-inline my-2 my-lg-0" asp-controller="Movies" asp-action="Filter" style="padding-right:25px;">
                        <input name="searchString" type="text" class="form-control" placeholder="Search for a movie.." />
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="bi bi-search"></i></button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid" style="margin-bottom:200px;">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center">
            &copy; 2023 - eMovieTickets
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>